### ISSUE TITLE
I can kill myself by hitting a "reverse direction" key combo too fast

### ISSUE THREAD

**Issue by Pomax** [chadsansing/color-picker-snake-game#14]
if I go left hit up/down=>right, or going right I hit up/down=>left, I reverse direction, but if I try the same when I'm going up and hit left/right=>down, or going down I hit left/right=>up, I get a game over, suggesting I actually turned "down" (or "up") before my left/right instruction finished processing.

**Comment by Pomax** [comment]
I suspect https://github.com/chadsansing/color-picker-snake-game/blob/master/scripts/game.js#L88-L108 is the cause here: you may want two different switches, based on whether the snake is travelling left/right or up/down, so that in the first case you evaluate up/down changes only, and if you're going up/down you evaluate left/right changes only, so that you can't process a "right" when going "left", or a "down" when going "up", so you can't run into yourself on the same tick (or so fast it's processed before the snake's been able to turn, based on clock time)

**Comment by chadsansing** [comment]
Good call; experienced the same; will attempt the fix!

**Comment by chadsansing** [comment]
Fixed w/ help from @flukeout.
