### ISSUE TITLE
Screen scrolls when lots of colours in list

### ISSUE THREAD

**Issue by secretrobotron** [chadsansing/color-picker-snake-game#21]
When the color list is long, trying to move the snake up and down makes the whole screen move. Super distracting when trying to crush high scores.

Using Chrome.

STR
1. Play the game for a while.
2. Grow the "My Colors" list to run off the bottom of the screen.
3. Using up/down controls the snake, but makes the screen scroll wildly as well.

cc @flukeout @chadsansing

I refuse to play this game obsessively until my high score can be reflective of my actual, unhindered skill.

**Comment by chadsansing** [comment]
Try again, @secretrobotron? I think we fixed this today in https://github.com/chadsansing/color-picker-snake-game/issues/17.

**Comment by chadsansing** [comment]
I see - when the list gets long enough, it scrolls the page down. You can scroll back to the top this will stop, but during play, additional children appended to the colors list scroll the page downwards. What works and where does it work? I've been messing w/ preventDefault() on different parts of colorList(), but I haven't found the solution yet. Onward.

**Comment by chadsansing** [comment]
Added a listener for "start-game" and prevented the default action afterwards when space is held or returned.
