### ISSUE TITLE
Laggy control response

### ISSUE THREAD

**Issue by secretrobotron** [chadsansing/color-picker-snake-game#22]
If you're really fast, you can beat the timing/logic and unintendedly crash into a wall. This is especially painful when your chain is huge and you're going for a dot right against a wall or in a corner.

STR
1. Go right.
2. Press up, then left, super fast.

(Replace "right" above with any direction, and try to do a 180.)

The snake won't turn :(. It just keeps motoring to the right.

**Comment by secretrobotron** [comment]
And the logic _is_ detecting my keypresses, but the snake isn't responding:

<img width="91" alt="screenshot 2016-05-09 15 21 34" src="https://cloud.githubusercontent.com/assets/403231/15125231/bd77f416-15f9-11e6-9af1-dbb4c7462d29.png">

:(

<img width="569" alt="screenshot 2016-05-09 15 22 11" src="https://cloud.githubusercontent.com/assets/403231/15125251/d281d6ec-15f9-11e6-802d-8cde8150ad95.png">

**Comment by secretrobotron** [comment]
On keydown, `snake.playerDirection = lastKey;` happens, but maybe queuing keys makes more sense.

**Comment by secretrobotron** [comment]
Also, a couple of times, I've been able to kill myself by pushing a certain combo of keys quickly. When I do, the snake is in a straight line in the middle of the screen, so I think I've been able to turn it back on itself. Like it's eating itself. Quite painful.

**Comment by secretrobotron** [comment]
cc @flukeout @chadsansing

**Comment by chadsansing** [comment]
Alright, @flukeout, let's try again? Maybe we can also fix that FPS hitch.

**Comment by flukeout** [comment]
@secretrobotron Curious about the STR to crash in yourself or suddenly die.

The way the controls work currently is that every time the snake moves, it checks for the last 'legal' direction set by the player. The snake can't move both down & right in one move (for example), so you have to time your moves so you press each of the direction keys right before the snake moves.

Queuing commands _could_ solve this, but I feel it would introduce a ton of unintended moves too. Like if you spam, left up right left down left in the span of one 'frame' the snake would then slowly go through that queue in the next 5 or 6 moves or wahtever before it started doing any of the "new" commands.

Let's dig into it on another call though.

**Comment by flukeout** [comment]
We can't really crank the FPS either, because the snake can only move one 'cube' at a time. If we jack the framerate, then the snake would move a lot faster right off the bat. Unless that's what we wanted. Turbosnake.

**Comment by flukeout** [comment]
@secretrobotron In that screenshot, the game didn't recognize ANY keypresses? That seems like a different bug than the turning one you were describing in the first comment.

**Comment by chadsansing** [comment]
The snake can't move faster than the frame rate or process moves more quickly without moving more quickly itself, so we're closing for now.

**Comment by secretrobotron** [comment]
Sorry dudes. Didn't see this in my inbox :(. Lemme try again to make sure.

**Comment by secretrobotron** [comment]
Yeah, this still happens on http://chadsansing.github.io/color-picker-snake-game/index.html. I can still be way faster than the turning logic.

**Comment by secretrobotron** [comment]
This game plays properly: http://www.me.umn.edu/~dockt036/snake.html

cc @flukeout

**Comment by flukeout** [comment]
Looks like that game indeed is queuing inputs, and just starts off at a higher framerate. Would be interesting to try a queue in our game, but have to be wary of how that feels with a slow initial speed.
