### ISSUE TITLE
[Bug] Randomly generated g and b values always display as the same

### ISSUE THREAD

**Issue by chadsansing** [chadsansing/color-picker-snake-game#3]
Something in one of the color functions is making the g and b values display as identical every time a new food is drawn. Is the problem here? What do you think, @flukeout?

![screen shot 2016-05-04 at 10 06 58 am](https://cloud.githubusercontent.com/assets/4128600/15016608/f8c3d40e-11df-11e6-9280-9c921c367c6d.png)

![screen shot 2016-05-04 at 9 18 27 am](https://cloud.githubusercontent.com/assets/4128600/15015321/390dea4c-11d9-11e6-9198-d0edb184a6d9.png)

![screen shot 2016-05-04 at 9 16 57 am](https://cloud.githubusercontent.com/assets/4128600/15016567/d6e7c55c-11df-11e6-9666-03f4f4544b67.png)

**Comment by flukeout** [comment]
@chadsansing Can I get some admin access to this here repo?

**Comment by chadsansing** [comment]
Made the b value the 3rd in the array, rather than making both the g and b values second.
